name: calculadora
description: "Calculadora simple para operaciones aritm√©ticas"
publish_to: 'none'
version: 1.1.2+6

environment:
  sdk: ^3.10.4

dependencies:
  decimal: ^3.2.4
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_md: ^0.0.8
  flutter_riverpod: ^3.1.0
  intl: ^0.20.2
  math_expressions: ^3.1.0
  shared_preferences: ^2.5.4
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/files/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf
