name: calculadora
description: "Calculadora simple para operaciones aritm√©ticas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  decimal: ^3.2.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  math_expressions: ^3.1.0
  shared_preferences: ^2.5.4
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
